ALTER TABLE CLIENT ADD PRIMARY KEY (CNO);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (DEPTNO) REFERENCES DEPARTMENT;

INSERT INTO EMPLOYEE VALUES ('E0006', 'JOSE', 'SECURITY', 'E0004', 'D004', '15-DEC-12', 500, 10000);

ALTER TABLE EMPLOYEE MODIFY JOB VARCHAR2(10) UNIQUE;

ALTER TABLE EMPLOYEE MODIFY EMPID CHECK(EMPID > 2000);

ALTER TABLE EMPLOYEE MODIFY SALARY DEFAULT 25000;

ALTER TABLE EMPLOYEE DROP UNIQUE(JOB);

SELECT constraint_name FROM all_constraints WHERE TABLE_NAME = 'EMPLOYEE';


INSERT INTO EMPLOYEE (EMPID, EMPNAME, JOB, MANAGER, DEPTNO, HIRDATE, COMMISSION) VALUES ('E0008', 'GARY', 'MASSEAUR', 'E0004', 'D004', '15-DEC-12', 500);