
SELECT SUM(DUEBALANCE) FROM CLIENT;

SELECT COUNT(EMPID) FROM EMPLOYEE;

SELECT MIN(DUEBALANCE), MAX(DUEBALANCE) FROM CLIENT;

SELECT AVG(SALARY) FROM EMPLOYEE;

SELECT NAME FROM CLIENT ORDER BY NAME;

SELECT DEPTNO, MAX(SALARY) FROM EMPLOYEE GROUP BY DEPTNO;

SELECT DEPTNO, MIN(SALARY) FROM EMPLOYEE WHERE DEPTNO!='D0001' GROUP BY DEPTNO;