
SELECT DEPTNO FROM DEPARTMENT UNION SELECT DEPTNO FROM EMPLOYEE;

SELECT DEPTNO FROM EMPLOYEE WHERE DEPTNO NOT IN (SELECT DEPTNO FROM DEPARTMENT);

SELECT * FROM EMPLOYEE WHERE EMPLOYEE.SALARY > (SELECT SALARY FROM EMPLOYEE WHERE EMPNAME='ASHOK');

SELECT * FROM EMPLOYEE WHERE EMPLOYEE.SALARY < (SELECT MIN(SALARY) FROM EMPLOYEE WHERE DEPTNO='D004');

SELECT * FROM EMPLOYEE WHERE EMPLOYEE.SALARY > (SELECT MIN(SALARY) FROM EMPLOYEE WHERE JOB LIKE'A%');

SELECT * FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.DEPTNO = DEPARTMENT.DEPTNO;

SELECT * FROM EMPLOYEE INNER JOIN DEPARTMENT ON EMPLOYEE.DEPTNO != DEPARTMENT.DEPTNO;

SELECT EMPNAME, JOB, MANAGER FROM DEPARTMENT LEFT JOIN EMPLOYEE ON EMPLOYEE.DEPTNO=DEPARTMENT.DEPTNO;

SELECT EMPNAME, JOB, MANAGER FROM DEPARTMENT RIGHT JOIN EMPLOYEE ON EMPLOYEE.DEPTNO=DEPARTMENT.DEPTNO;

SELECT EMPNAME, JOB, MANAGER FROM DEPARTMENT FULL JOIN EMPLOYEE ON EMPLOYEE.DEPTNO=DEPARTMENT.DEPTNO;