ALTER TABLE CLIENT ADD PRIMARY KEY (CNO);

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE DEPTNO;

INSERT INTO EMPLOYEE VALUES ();

ALTER TABLE EMPLOYEE MODIFY JOB VARCHAR2(10) UNIQUE;

ALTER TABLE EMPLOYEE MODIFY EMPID NUMBER(5) PRIMARY KEY CHECK (EMPID > 2000);

ALTER TABLE EMPLOYEE MODIFY SAL NUMBER(7, 3) DEFAULT 25000;

ALTER TABLE EMPLOYEE MODIFY COLUMN JOB DROP UNIQUE;

SELECT constraint_name FROM all_constraints WHERE TABLE_NAME = EMPLOYEE;