ALTER TABLE EMPLOYEE MODIFY EMPID VARCHAR2(5);
ALTER TABLE EMPLOYEE MODIFY MANAGER VARCHAR2(5);
ALTER TABLE EMPLOYEE MODIFY DEPTNO VARCHAR2(5);
ALTER TABLE EMPLOYEE MODIFY SALARY NUMBER(7, 1);

DESC EMPLOYEE

INSERT INTO EMPLOYEE VALUES ('E0001', 'ABEY', 'TESTER', 'E0004', 'D004', '15-DEC-12', 500, 30000);
INSERT INTO EMPLOYEE VALUES ('E0002', 'JESTO', 'ANALYST', 'E0001', 'D002', '24-APR-2011', 650, 25000);
INSERT INTO EMPLOYEE VALUES ('E0003', 'ADARSH', 'CLERK', 'E0004', 'D004', '10-JAN-2013', 500, 15000);
INSERT INTO EMPLOYEE VALUES ('E0004', 'KEVIN', 'ADMIN', 'E0005', 'D002', '10-DEC-2013', 1750, 20000);
INSERT INTO EMPLOYEE (EMPID, EMPNAME, JOB, DEPTNO, HIRDATE, COMMISSION, SALARY) VALUES ('E0005', 'BONY', 'MANAGER', 'D001', '11-APR-2011', 1000, 50000);
INSERT INTO EMPLOYEE VALUES ('E0006', 'MANU', 'SUPPLIER', 'E0003', 'D004', '19-JUN-2013', 450, 5000);

CREATE TABLE DEPARTMENT (
    DEPTNO VARCHAR(5) PRIMARY KEY,
    DEPTNAME VARCHAR(20),
    LOCATION VARCHAR(30)
);

DESC DEPARTMENT;

INSERT INTO DEPARTMENT VALUES ('D001', 'DEPTA', 'A BLOCK');
INSERT INTO DEPARTMENT VALUES ('D002', 'DEPTB', 'B BLOCK');
INSERT INTO DEPARTMENT VALUES ('D003', 'DEPTC', 'C BLOCK');
INSERT INTO DEPARTMENT VALUES ('D004', 'DEPTD', 'D BLOCK');


CREATE TABLE CLIENT (
    CNO VARCHAR2(6) PRIMARY KEY,
    NAME VARCHAR2(20),
    ADDRESS VARCHAR2(30),
    CITY VARCHAR2(15),
    PINCODE NUMBER(8),
    STATE VARCHAR2(15),
    BALDUE NUMBER(10, 2)
);

DESC CLIENT;

INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C01', 'NIMMY', 'COCHIN', 680324, 'KERALA', 14000);
INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C02', 'SUSAN', 'COCHIN', 680324, 'KERALA', 0);
INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C03', 'ANJANA', 'SALEM', 680345, 'TAMILNADU', 5000);
INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C04', 'SNEHA', 'PUNE', 680223, 'MAHARASHTRA', 500);
INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C05', 'ANNET', 'GANDIPURAM', 680321, 'KARNATAKA', 7600);
INSERT INTO CLIENT (CNO, NAME, CITY, PINCODE, STATE, BALDUE) VALUES ('C06', 'ANN', 'BOMBAY', 682111, 'MAHARASHTRA', 2055);


SELECT * FROM EMPLOYEE;
SELECT * FROM DEP;
SELECT * FROM CLIENT;



SELECT * FROM CLIENT FETCH FIRST 4 ROWS ONLY;

SELECT EMPNAME, HIRDATE, SALARY FROM EMPLOYEE;

SELECT EMPNAME FROM EMPLOYEE WHERE EMPNAME LIKE 'A%' OR EMPNAME LIKE 'K%';

SELECT DISTINCT CITY FROM CLIENT;

SELECT EMPNAME FROM EMPLOYEE WHERE HIRDATE >= '31-DEC-2012' AND SALARY > 17500 AND JOB = 'MANAGER';

SELECT EMPNAME FROM EMPLOYEE WHERE EMPNAME >= 'E%' AND EMPNAME <= 'L%';

UPDATE CLIENT SET CITY = 'DELHI' WHERE CNO = 'C03';

UPDATE CLIENT SET BALDUE = 600 WHERE NAME = 'SUSAN';

SELECT NAME, 'FROM', CITY, 'HAS', BALDUE, 'BALANCE DUE' FROM CLIENT; 

ALTER TABLE CLIENT RENAME COLUMN BALDUE TO DUEBALANCE;

SELECT NAME FROM CLIENT WHERE STATE != 'KERALA';